[package]
name = "pipelined-core"
version = "0.1.0"
authors = ["Evan Cameron <evan@vectorface.com>"]

[dependencies]
bytes = "0.4"
tokio-io = "0.1"
tokio-proto = "0.1"
tokio-core = "0.1"
tokio-service = "0.1"
futures = "0.1"
