[package]
name = "tunstenite-tokio"
version = "0.1.0"
authors = ["Evan Cameron <evan@vectorface.com>"]

[dependencies]
tokio-timer = "0.1"
tokio-core = "0.1"
tungstenite = "0.2"
tokio-tungstenite = "0.2"
futures = "0.1"
futures-cpupool = "0.1"