[package]
name = "multiple-cores"
version = "0.1.0"
authors = ["Evan Cameron <evan@vectorface.com>"]

[dependencies]
error-chain = "0.10"
futures = "0.1"
num_cpus = "1"
tokio-core = "0.1"
tokio-io = "0.1"
