[package]
name = "tls-core"
version = "0.1.0"
authors = ["Evan Cameron <evan@vectorface.com>"]

[dependencies]
tokio-io = "0.1"
tokio-core = "0.1"
tokio-tls = "0.1"
native-tls = "0.1"
futures = "0.1"
